name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Inject Firebase Keys
      run: |
        # Overwrite the production environment file with real values
        cat <<EOF > ./smt-frontend/src/environments/environment.prod.ts
        export const environment = {
          production: true,
          firebase: ${{ secrets.FIREBASE_CONFIG }}
        };
        EOF
        # create a basic environment.ts to prevent compiler errors
        echo "export const environment = { production: false, firebase: {} };" > ./smt-frontend/src/environments/environment.ts

    - name: Login to Docker Hub
      uses: docker/login-action@v3
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}
        
    - name: Build & Push Backend
      uses: docker/build-push-action@v5
      with:
        context: ./SMT
        push: true
        tags: |
          ${{ secrets.DOCKERHUB_USERNAME }}/smt_oms:backend
          ${{ secrets.DOCKERHUB_USERNAME }}/smt_oms:backend-${{ github.sha }}
          
    - name: Build & Push Frontend
      uses: docker/build-push-action@v5
      with:
        context: ./smt-frontend
        push: true
        tags: |
          ${{ secrets.DOCKERHUB_USERNAME }}/smt_oms:frontend
          ${{ secrets.DOCKERHUB_USERNAME }}/smt_oms:frontend-${{ github.sha }}
